version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"

  nats:
    image: nats:latest
    container_name: nats_server
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "8222:8222" # (옵션) NATS 웹 UI를 위한 포트
